version: '2'
services:
    newsfeed:
        container_name: infra_newsfeed
        image: newsfeed
        command: java -jar /root/newsfeed.jar
        ports:
          - "8002:8002"
        environment:
           APP_PORT: "8002" 
    quotes:
        container_name: infra_quotes
        image: quotes
        command: java -jar /root/quotes.jar
        ports:
          - "8001:8001"
        environment:
           APP_PORT: "8001"
    static-assets:
        container_name: static_assets
        image: static-asset
        command: /root/serve.py
        ports:
          - "8000:8000"
    frontend:
        container_name: infra_frontend
        image: frontend
        command: java -jar /root/front-end.jar
        ports:
          - "8003:8003"
            #links:
            #- newsfeed
            #- quotes
            #- static-assets
        environment:
           APP_PORT: "8003"
           STATIC_URL: http://static-assets:8000
           QUOTE_SERVICE_URL: http://quotes:8001
           NEWSFEED_SERVICE_URL: http://newsfeed:8002
           NEWSFEED_SERVICE_TOKEN: T1&eWbYXNWG1w1^YGKDPxAWJ@^et^&kX
